export const MOCK_PROPERTY_DATA = {
  id: "prop-123456",
  title: "3BHK House For Sale – Abhyankar Nagar",
  price: "1.25 Cr",
  pricePerSqFt: "7,500",
  propertyType: "Apartment",
  transactionType: "New Property",
  bedrooms: 3,
  bathrooms: 2,
  balconies: 1,
  description: "A beautiful 3BHK apartment in Abhyankar Nagar with modern amenities and excellent connectivity. The apartment is part of a gated community with 24x7 security, power backup, and water supply. The property features premium finishes, spacious rooms, and is close to schools, hospitals, and shopping centers.",
  carpetArea: 1450,
  builtUpArea: 1800,
  superBuiltUpArea: 2100,
  balconyArea: "120 sq.ft",
  furnishingStatus: "Semi-Furnished",
  ageOfProperty: "New Construction",
  possessionStatus: "Ready to move",
  totalFloors: 12,
  floorNumber: 8,
  facing: "East",
  ownershipType: "Freehold",
  maintenance: 3500,
  amenities: [
    "Power Backup",
    "24x7 Water Supply",
    "WiFi Connectivity",
    "Security",
    "Gym",
    "Parking",
    "Garden",
    "Park",
    "Storage",
    "Bicycle Stand",
    "Lift",
    "Fire Safety"
  ],
  keyFeatures: [
    "Vastu Compliant",
    "Good Natural Light",
    "Cross Ventilation",
    "Spacious Rooms",
    "Premium Fittings"
  ],
  coveredParking: 1,
  openParking: 1,
  images: [
    "https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg",
    "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg",
    "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg",
    "https://images.pexels.com/photos/1648776/pexels-photo-1648776.jpeg",
    "https://images.pexels.com/photos/1743227/pexels-photo-1743227.jpeg",
    "https://images.pexels.com/photos/1029599/pexels-photo-1029599.jpeg",
    "https://images.pexels.com/photos/2724748/pexels-photo-2724748.jpeg",
    "https://images.pexels.com/photos/276554/pexels-photo-276554.jpeg"
  ],
  location: {
    address: "Abhyankar Nagar, Near City Hospital",
    city: "Nagpur",
    state: "Maharashtra",
    pinCode: "440010",
    landmark: "Near City Hospital",
    locality: "Abhyankar Nagar",
    latitude: 21.1458,
    longitude: 79.0882
  },
  owner: {
    name: "Shravani Patil",
    type: "Agent",
    phone: "9834371949",
    email: "shravani@example.com",
    profileImage: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg"
  },
  listedBy: "Owner",
  listedOn: "2023-05-15",
  reraNumber: "REG/MAH/2023/12345"
};